### ISSUE TITLE
Join the org

### ISSUE THREAD

**Issue by VasudevJaiswal** [AmineAML/AmineAML#1]
[Click Here](https://github.com/Jaidevstudio)

**Comment by AmineAML** [comment]
Ok, send me an invitation

**Comment by VasudevJaiswal** [comment]
@AmineAML 
1. Firstly fill details [Click Here](https://github.com/Jaidevstudio/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization)
2. And check your email or [Page](https://github.com/jaidevstudio)

**Comment by AmineAML** [comment]
Done, thank you for the invite!
